### ISSUE TITLE
Patch on kernel

### ISSUE THREAD

**Issue by mhalano** [vogelchr/led-notify-module#1]
This patch already is on kernel?

**Comment by vogelchr** [comment]
Yes, this has been merged since a long time. Right now, the code lives in...

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/hid/hid-led.c

**Comment by vogelchr** [comment]
Note that this now allows using the "Webmail Notifier" as a regular Linux-LED, including all triggers, for example:

    echo disk-activity >/sys/class/leds/riso_kagaku2:green/trigger 

turns the "webmail notifier" into a harddisk-activity light.
